TARGET_MANUFACTURER_NAME := nxpp 
TARGET_DEVICE_NAME := imx88
SOURCE_MANUFACTURER_NAME := imx8m
SOURCE_DEVICE_NAME :=  evk_8mq

SOURCE_ANDROID_PATH := /home/krishna/AOSP_P_IMX_PORT/patch_source_nxp
TARGET_ANDROID_PATH := /home/krishna/AOSP_P_IMX_PORT/my_IMX 

TARGET_PLATFORM := nxp
