CC = gcc
#OBJ = main.o fun1.o fun2.o  
OBJ += main.c fun1.c fun2.c
.PHONY: clean 


all:  

	$ {CC} $(OBJ)  -o clean 

#first : main1.c fun1.c fun2.c
#	$(CC)  -c	$^  		
list :

clean :

	-rm -rf *.o  clean 
